version: '3.4'

volumes:
  test_data:

services:
  station:
    build:
      context: .
      target: station
    ports:
      - "4444:4444"

  db:
    image: couchdb:3.1
    volumes:
      - test_data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=testmaster
      - COUCHDB_PASSWORD=testmastertest
    ports:
      - "5984:5984"

