version: '3.4'

volumes:
  test_data:

services:
  station:
    build:
      context: .
      target: station
    ports:
      - "4444:4444"

  db:
    image: couchdb:3.1
    volumes:
      - type: volume
        source: test_data
        target: /opt/couchdb/data
      - type: bind
        source: ./couchdb
        target: /opt/couchdb/etc/local.d
    environment:
      - COUCHDB_USER=testmaster
      - COUCHDB_PASSWORD=testmastertest
    ports:
      - "5984:5984"

